{
    "name": "Raport Ambalaje",
    "category": "Product",
    "summary": "",
    "version": "12.0.1.0.0",
    "author": "Terrabit",
    "license": "LGPL-3",
    "website": "https://www.terrabit.ro",
    "depends": ["base", "product"],
    "data": ["views/raport_view.xml", "security/ir.model.access.csv"],
    "images": ["static/icon.png"],
    "installable": True,
    "development_status": "stable",
    "maintainers": ["CDaniel"],
}
