coverage:
  status:
    project:
      default:
        target: 65% # the required coverage value
        threshold: 10% # the leniency in hitting the target
    patch:
      default:
        target: auto
        threshold: 10% # the leniency in hitting the target
