{
    "name": "Stock Auto Transfer",
    "version": "18.0.0.0.15",
    "author": "Terrabit, Voicu Stefan",
    "website": "https://www.terrabit.ro",
    "category": "Warehouse",
    "summary": "Automate internal transfer from transit location",
    "depends": ["stock"],
    "license": "LGPL-3",
    "data": [
        "security/ir.model.access.csv",
        "views/stock_picking_views.xml",
        "wizard/stock_picking_transfer_wizard_views.xml",
        "views/stock_picking_type_view.xml",
    ],
    "development_status": "Beta",
    "post_init_hook": "post_init_hook",
    "maintainers": ["VoicuStefan2001"],
    "images": ["static/description/main_screenshot.png"],
}
