{
    "name": "Stock Move Pivot Table",
    "version": "15.0.0.0.0",
    "summary": "Pivot table for stock moves by provider/customer and product",
    "author": "Terrabit, Voicu Stefan",
    "website": "https://www.terrabit.ro",
    "license": "OPL-1",
    "category": "Warehouse",
    "depends": ["stock"],
    "data": ["security/ir.model.access.csv", "wizard/stock_move_report_wizard_view.xml"],
    "images": ["static/description/main_screenshot.png"],
    "installable": True,
    "application": False,
    "development_status": "Beta",
    "maintainers": ["VoicuStefan2001"],
}
