def migrate(cr, version):
    """Flag the extra lines generated by the previous versions.

    A pair is two lines of the same order sharing a `line_uuid`; the extra line is
    always created after its main line, so it is the one with the greater id. The
    product is deliberately not checked: a pair whose main product was changed
    (PURCHASEEXTRA-001) must still be recognized, so that the stale extra line is
    replaced on the next synchronization.
    """
    if not version:
        return
    cr.execute(
        """
        UPDATE purchase_order_line extra
           SET is_extra_line = TRUE
          FROM purchase_order_line main
         WHERE extra.line_uuid IS NOT NULL
           AND extra.line_uuid = main.line_uuid
           AND extra.order_id = main.order_id
           AND extra.id > main.id
        """
    )
