# © 2025 Deltatech
#              Dorin Hongu <dhongu(@)gmail(.)com
# See README.rst file on addons root folder for license details

import uuid

from odoo import api, fields, models


class PurchaseOrder(models.Model):
    _inherit = "purchase.order"

    def write(self, vals):
        if "order_line" not in vals:
            return super().write(vals)
        # The lines are synchronized once all the commands are applied: a line updated
        # by a command cannot see the extra line that a later command of the same save
        # creates (the one generated by the form's onchange), and would duplicate it.
        res = super(PurchaseOrder, self.with_context(skip_check_extra_product=True)).write(vals)
        if not self.env.context.get("skip_check_extra_product"):
            self.order_line.check_extra_product()
        return res

    def action_rfq_send(self):
        self.order_line.with_context(backend=True).check_extra_product()
        return super().action_rfq_send()

    @api.onchange("order_line")
    def onchange_order_line(self):
        """
        Update extra product in backend
        :return: super
        """
        obsolete_lines = self.order_line.with_context(backend=True).check_extra_product()
        if obsolete_lines:
            self.order_line -= obsolete_lines


class PurchaseOrderLine(models.Model):
    _inherit = "purchase.order.line"

    line_uuid = fields.Char()
    is_extra_line = fields.Boolean(
        help="Technical field: this line was generated as the extra line of the main line "
        "sharing its line_uuid, so it is replaced or removed when the main product changes.",
    )
    extra_price_computed = fields.Float(
        digits="Product Price",
        copy=False,
        help="Technical field: last unit price computed for this extra line. "
        "A unit price that differs from it was set by the user and is kept as is.",
    )

    @api.model_create_multi
    def create(self, vals_list):
        res = super().create(vals_list)
        for line in res:
            line.check_extra_product()
        return res

    def write(self, vals):
        res = super().write(vals)
        # A quantity/price/product change saved outside the form's live onchange
        # (inline list edit, import, RPC write) never went through
        # `check_extra_product`, so the extra line silently kept its old
        # quantity/price (ticket #9275). `skip_check_extra_product` guards the
        # recursion this triggers: `check_extra_product` writes back on the
        # extra line (and, through PTC's override, sometimes on this same line).
        if not self.env.context.get("skip_check_extra_product") and vals.keys() & {
            "product_qty",
            "product_id",
            "price_unit",
        }:
            self.with_context(skip_check_extra_product=True).check_extra_product()
        return res

    def _get_extra_line(self):
        """Return the extra line generated for this main line, if any."""
        self.ensure_one()
        if not self.line_uuid or self.is_extra_line:
            return self.browse()
        return self.order_id.order_line.filtered(
            lambda l: l.is_extra_line and l.line_uuid == self.line_uuid and l.id != self.id
        )

    def unlink(self):
        # Saving a form where the main product was changed sends a delete command for
        # the obsolete extra line, which the `write()` of the main line, processed in
        # the same save, may already have removed through `check_extra_product`.
        lines = self.exists()
        # the pair is found through `is_extra_line`, not through the current product
        # configuration: a main line whose product no longer has an extra still owns it
        extra_lines = self.browse()
        for line in lines:
            extra_lines |= line._get_extra_line()
        extra_lines -= lines
        if extra_lines:
            extra_lines.unlink()
        return super(PurchaseOrderLine, lines).unlink()

    def _has_manual_price(self):
        """Tell whether the unit price of this extra line was set by the user.

        The price is considered manual when it matches neither what this module
        computed last (``extra_price_computed``) nor what the standard price
        computation wrote (``technical_price_unit``, which the standard keeps
        equal to ``price_unit``, so a vendor price recomputation is not mistaken
        for a manual price).
        """
        self.ensure_one()
        # `currency_id` can be False on NewId records
        currency = self.currency_id or self.company_id.currency_id or self.env.company.currency_id
        return bool(
            currency.compare_amounts(self.extra_price_computed, self.price_unit)
            and currency.compare_amounts(self.technical_price_unit, self.price_unit)
        )

    def check_extra_product(self):
        """Synchronize the extra line of each main line with its current product.

        An extra line generated for another product than the current extra product of
        the main line (the main product was changed, or no longer has an extra) is
        removed, and a new one is generated when needed. Records being edited in a
        form (``NewId``) cannot be deleted from here: they are returned, so that the
        caller removes them from the order lines.

        :return: the obsolete extra lines that are still to be removed
        """
        obsolete_lines = self.browse()
        for line in self:
            if line.is_extra_line:
                continue
            if line.order_id.state not in ["draft", "sent"]:
                continue
            extra_product = line.product_id.extra_product_id
            extra_line_id = line._get_extra_line()
            if extra_line_id and extra_line_id.product_id != extra_product:
                obsolete_lines |= extra_line_id
                extra_line_id = self.browse()
            if not extra_product:
                continue
            new_line = not extra_line_id
            if new_line:
                new_uuid = str(uuid.uuid4())
                values = {
                    "product_qty": line.product_qty * (line.product_id.extra_qty or 1.0),
                    "product_id": extra_product.id,
                    "uom_id": extra_product.uom_id.id,
                    "order_id": line.order_id.id,
                    "sequence": line.sequence + 1,
                    "line_uuid": new_uuid,
                    "is_extra_line": True,
                }
                backend = self.env.context.get("backend", False)
                if backend:
                    extra_line_id = line.order_id.order_line.new(values)
                else:
                    extra_line_id = line.order_id.order_line.create(values)
                line.line_uuid = new_uuid
            product_qty = line.product_qty * (line.product_id.extra_qty or 1.0)
            if product_qty != extra_line_id.product_qty:
                extra_line_id.product_qty = product_qty
            if not line.product_id.extra_percent:
                continue
            # a price typed in on the extra line wins over the computed one, until the
            # extra line is deleted (it is then regenerated with the computed price)
            if not new_line and extra_line_id._has_manual_price():
                continue
            price_unit = line.price_unit * (line.product_id.extra_percent or 0.0) / 100.0
            # keep track of the price we set, so that a later manual change is recognized
            extra_line_id.update({"price_unit": price_unit, "extra_price_computed": price_unit})
        stored_lines = obsolete_lines.filtered(lambda l: isinstance(l.id, int))
        if stored_lines:
            stored_lines.unlink()
        return obsolete_lines - stored_lines
