# © 2025 Deltatech
# See README.rst file on addons root folder for license details

from odoo.tests.common import TransactionCase


class TestBusinessProcess(TransactionCase):
    def setUp(self):
        super().setUp()
        # Minimal partner for responsibility fields
        self.partner = self.env["res.partner"].search([], limit=1)
        if not self.partner:
            self.partner = self.env["res.partner"].create({"name": "Tester"})

        # Create a business area and optional group
        self.area = self.env["business.area"].create(
            {
                "name": "ERP",
                "responsible_id": self.partner.id,
            }
        )
        self.group = self.env["business.process.group"].create(
            {
                "name": "Sales",
                "area_id": self.area.id,
            }
        )

        # Create a business project (keep default project_type=remote to avoid install modules path)
        self.project = self.env["business.project"].create(
            {
                "name": "Implementation",
                "customer_id": self.partner.id,
                "project_type": "remote",
            }
        )

        # Create a business process
        self.process = self.env["business.process"].create(
            {
                "name": "Order to Cash",
                "area_id": self.area.id,
                "process_group_id": self.group.id,
                "project_id": self.project.id,
                "responsible_id": self.partner.id,
                "customer_id": self.partner.id,
            }
        )

    def test_step_sequence_and_display_name(self):
        # Create step without code to force sequence-generated code
        step = self.env["business.process.step"].create(
            {
                "name": "Create Sales Order",
                "process_id": self.process.id,
            }
        )
        self.assertTrue(step.code, "Step code should be auto-generated by sequence")
        # display_name should include [CODE] prefix if code exists
        self.assertIn("[", step.display_name)
        self.assertIn("]", step.display_name)
        self.assertIn("Create Sales Order", step.display_name)

    def test_process_computed_counts_and_actions(self):
        # Initially no steps/tests/developments
        self.process._compute_count_steps()
        self.process._compute_count_tests()
        self.process._compute_count_developments()
        self.assertEqual(self.process.count_steps, 0)
        self.assertEqual(self.process.count_tests, 0)
        self.assertEqual(self.process.count_developments, 0)

        # Add one step and recompute
        step = self.env["business.process.step"].create(
            {
                "name": "Validate Order",
                "process_id": self.process.id,
            }
        )
        self.process._compute_count_steps()
        self.assertEqual(self.process.count_steps, 1)

        # Link a development through the step to cover _compute_developments and count
        # Create minimal development type and development
        dev_type = self.env["business.development.type"].create({"name": "Python"})
        development = self.env["business.development"].create(
            {
                "name": "Auto-confirm",
                "area_id": self.area.id,
                "type_id": dev_type.id,
            }
        )
        step.development_ids = [(6, 0, development.ids)]
        self.process._compute_developments()
        self.process._compute_count_developments()
        self.assertIn(development, self.process.development_ids)
        self.assertEqual(self.process.count_developments, 1)

        # action_view_steps returns a proper action dict with domain/context
        action_steps = self.process.action_view_steps()
        self.assertIsInstance(action_steps, dict)
        self.assertIn("domain", action_steps)
        self.assertIn("context", action_steps)
        self.assertIn(("process_id", "=", self.process.id), action_steps["domain"])

        # action_view_tests returns a proper action dict as well
        action_tests = self.process.action_view_tests()
        self.assertIsInstance(action_tests, dict)
        self.assertIn("domain", action_tests)
        self.assertIn("context", action_tests)
        self.assertIn(("process_id", "=", self.process.id), action_tests["domain"])

        # action_view_developments returns developments filtered by the process' development_ids
        action_devs = self.process.action_view_developments()
        self.assertIsInstance(action_devs, dict)
        self.assertIn("domain", action_devs)
        self.assertIn("context", action_devs)

    def test_duration_for_completion_compute(self):
        self.process.write(
            {
                "configuration_duration": 1.5,
                "instructing_duration": 2.0,
                "data_migration_duration": 0.5,
                "testing_duration": 3.0,
            }
        )
        self.process._compute_duration_for_completion()
        self.assertEqual(self.process.duration_for_completion, 7.0)

    def test_name_search_by_code_and_name(self):
        # Ensure a code is generated for process by simulating create without code
        # code is optional; name_search searches first by code via Domain.AND
        # set a code to a known value
        self.process.write({"code": "BP-001"})
        res = self.env["business.process"].name_search("BP-001")
        # Result is list of tuples (id, display_name)
        self.assertTrue(any(r[0] == self.process.id for r in res))

        # Searching by a non-matching code should return empty or other results not ours
        res2 = self.env["business.process"].name_search("NONEXISTENT-CODE")
        self.assertTrue(all(r[0] != self.process.id for r in res2))
