# © 2025 Deltatech
# See README.rst file on addons root folder for license details

from odoo.exceptions import UserError
from odoo.tests.common import TransactionCase


class TestBusinessProcess(TransactionCase):
    def setUp(self):
        super().setUp()
        # Minimal partner for responsibility fields
        self.partner = self.env["res.partner"].search([], limit=1)
        if not self.partner:
            self.partner = self.env["res.partner"].create({"name": "Tester"})

        # Create a business area and optional group
        self.area = self.env["business.area"].create(
            {
                "name": "ERP",
                "responsible_id": self.partner.id,
            }
        )
        self.group = self.env["business.process.group"].create(
            {
                "name": "Sales",
                "area_id": self.area.id,
            }
        )

        # Create a business project (keep default project_type=remote to avoid install modules path)
        self.project = self.env["business.project"].create(
            {
                "name": "Implementation",
                "customer_id": self.partner.id,
                "project_type": "remote",
            }
        )

        # Create a business process
        self.process = self.env["business.process"].create(
            {
                "name": "Order to Cash",
                "area_id": self.area.id,
                "process_group_id": self.group.id,
                "project_id": self.project.id,
                "responsible_id": self.partner.id,
                "customer_id": self.partner.id,
            }
        )

    def test_step_sequence_and_display_name(self):
        # Create step without code to force sequence-generated code
        step = self.env["business.process.step"].create(
            {
                "name": "Create Sales Order",
                "process_id": self.process.id,
            }
        )
        self.assertTrue(step.code, "Step code should be auto-generated by sequence")
        # display_name should include [CODE] prefix if code exists
        self.assertIn("[", step.display_name)
        self.assertIn("]", step.display_name)
        self.assertIn("Create Sales Order", step.display_name)

    def test_process_computed_counts_and_actions(self):
        # Initially no steps/tests/developments
        self.process._compute_count_steps()
        self.process._compute_count_tests()
        self.process._compute_count_developments()
        self.assertEqual(self.process.count_steps, 0)
        self.assertEqual(self.process.count_tests, 0)
        self.assertEqual(self.process.count_developments, 0)

        # Add one step and recompute
        step = self.env["business.process.step"].create(
            {
                "name": "Validate Order",
                "process_id": self.process.id,
            }
        )
        self.process._compute_count_steps()
        self.assertEqual(self.process.count_steps, 1)

        # Link a development through the step to cover _compute_developments and count
        # Create minimal development type and development
        dev_type = self.env["business.development.type"].create({"name": "Python"})
        development = self.env["business.development"].create(
            {
                "name": "Auto-confirm",
                "area_id": self.area.id,
                "type_id": dev_type.id,
            }
        )
        step.development_ids = [(6, 0, development.ids)]
        self.process._compute_developments()
        self.process._compute_count_developments()
        self.assertIn(development, self.process.development_ids)
        self.assertEqual(self.process.count_developments, 1)

        # action_view_steps returns a proper action dict with domain/context
        action_steps = self.process.action_view_steps()
        self.assertIsInstance(action_steps, dict)
        self.assertIn("domain", action_steps)
        self.assertIn("context", action_steps)
        self.assertIn(("process_id", "=", self.process.id), action_steps["domain"])

        # action_view_tests returns a proper action dict as well
        action_tests = self.process.action_view_tests()
        self.assertIsInstance(action_tests, dict)
        self.assertIn("domain", action_tests)
        self.assertIn("context", action_tests)
        self.assertIn(("process_id", "=", self.process.id), action_tests["domain"])

        # action_view_developments returns developments filtered by the process' development_ids
        action_devs = self.process.action_view_developments()
        self.assertIsInstance(action_devs, dict)
        self.assertIn("domain", action_devs)
        self.assertIn("context", action_devs)

    def test_duration_for_completion_compute(self):
        self.process.write(
            {
                "configuration_duration": 1.5,
                "instructing_duration": 2.0,
                "data_migration_duration": 0.5,
                "testing_duration": 3.0,
            }
        )
        self.process._compute_duration_for_completion()
        self.assertEqual(self.process.duration_for_completion, 7.0)

    def test_name_search_by_code_and_name(self):
        # Ensure a code is generated for process by simulating create without code
        # code is optional; name_search searches first by code via Domain.AND
        # set a code to a known value
        self.process.write({"code": "BP-001"})
        res = self.env["business.process"].name_search("BP-001")
        # Result is list of tuples (id, display_name)
        self.assertTrue(any(r[0] == self.process.id for r in res))

        # Searching by a non-matching code should return empty or other results not ours
        res2 = self.env["business.process"].name_search("NONEXISTENT-CODE")
        self.assertTrue(all(r[0] != self.process.id for r in res2))

    def test_action_view_acceptance_tests_behaviour(self):
        # Initially, no acceptance tests; calling action should auto-create one and return correct action
        self.process.count_acceptance_tests = 0  # ensure branch
        action = self.process.action_view_acceptance_tests()
        self.assertIsInstance(action, dict)
        # After the call, there should be at least one acceptance test
        tests = self.env["business.process.test"].search(
            [
                ("process_id", "=", self.process.id),
                ("scope", "=", "user_acceptance"),
            ]
        )
        self.assertGreaterEqual(len(tests), 1)

    def test_attachment_domain_and_doc_count(self):
        Attachment = self.env["ir.attachment"].sudo()
        # Attachment directly on process
        p_att = Attachment.create(
            {
                "name": "p.txt",
                "res_model": "business.process",
                "res_id": self.process.id,
                "datas": "Y29udGVudA==",
                "mimetype": "text/plain",
            }
        )
        # Create a test and attach to it
        test = self.env["business.process.test"].create(
            {
                "name": "UAT",
                "process_id": self.process.id,
                "scope": "user_acceptance",
            }
        )
        t_att = Attachment.create(
            {
                "name": "t.txt",
                "res_model": test._name,
                "res_id": test.id,
                "datas": "Y29udGVudA==",
                "mimetype": "text/plain",
            }
        )
        domain = self.process.get_attachment_domain()
        # Both attachments should match the domain filter (OR of process and tests)
        matches = Attachment.search(domain)
        self.assertIn(p_att, matches)
        self.assertIn(t_att, matches)
        self.process._compute_attached_docs_count()
        self.assertGreaterEqual(self.process.doc_count, 1)
        act = self.process.attachment_tree_view()
        self.assertEqual(act.get("res_model"), "ir.attachment")
        self.assertEqual(act.get("type"), "ir.actions.act_window")

    def test_state_transition_buttons(self):
        # start design sets state and possibly date_start_bbp
        self.process.button_start_design()
        self.assertEqual(self.process.state, "design")
        self.assertTrue(self.process.date_start_bbp)
        # start test moves to test and sets end date/completion if not set
        self.process.date_end_bbp = False
        self.process.completion_bbp = 0.0
        self.process.button_start_test()
        self.assertEqual(self.process.state, "test")
        self.assertTrue(self.process.date_end_bbp)
        self.assertEqual(self.process.completion_bbp, 100.0)
        # end test -> ready
        self.process.button_end_test()
        self.assertEqual(self.process.state, "ready")
        # go live -> production
        self.process.button_go_live()
        self.assertEqual(self.process.state, "production")
        # back to draft
        self.process.button_draft()
        self.assertEqual(self.process.state, "draft")
        # abandon
        self.process.button_abandon()
        self.assertEqual(self.process.state, "abandoned")

    def test_start_tests_helpers_create_tests(self):
        # Ensure no tests exist of these scopes
        self.env["business.process.test"].search([("process_id", "=", self.process.id)]).unlink()
        self.process.start_internal_test()
        self.process.start_integration_test()
        self.process.start_user_acceptance_test()
        scopes = self.env["business.process.test"].search([("process_id", "=", self.process.id)]).mapped("scope")
        for s in ("internal", "integration", "user_acceptance"):
            self.assertIn(s, scopes)

    def test_button_install_modules_constraints(self):
        # Not local project -> should raise
        with self.assertRaises(UserError):
            self.process.button_install_modules()
        # Make project local and ensure it returns a notification when no modules pending
        self.process.project_id.project_type = "local"
        notif = self.process.button_install_modules()
        self.assertIsInstance(notif, dict)
        self.assertEqual(notif.get("type"), "ir.actions.client")
