from odoo.tools import SQL


def migrate(cr, version):
    """Flag the extra lines generated by the previous versions.

    They were told apart from their main line only by the configuration of the
    product. Of the two lines sharing a UUID, the extra line is the one created
    last; the product is not checked, so that pairs already broken by a product
    change are recognized as well.
    """
    if not version:
        return
    cr.execute(
        SQL(
            """
            UPDATE sale_order_line
               SET is_extra_line = TRUE
             WHERE id IN (
                    SELECT MAX(id)
                      FROM sale_order_line
                     WHERE line_uuid IS NOT NULL
                     GROUP BY order_id, line_uuid
                    HAVING COUNT(*) = 2
             )
            """
        )
    )
