def migrate(cr, version):
    """Adopt the price of the extra lines generated by the previous versions.

    Without this, their `extra_price_computed` would stay at zero and every one of
    them would be taken for a manually priced line, so the price would stop
    following the main line.
    """
    if not version:
        return
    cr.execute(
        """
        UPDATE sale_order_line
           SET extra_price_computed = price_unit
         WHERE line_uuid IS NOT NULL
           AND extra_price_computed = 0
        """
    )
