from . import test_cron_pdfs
from . import test_picking_cron_pdfs
from . import test_force_cancel
from . import test_cron_xml
from . import test_cron_old_messages
from . import test_invoice_cron_pdfs
from . import test_res_partner
from . import test_cron_from_settings
from . import test_run_now_button
from . import test_cron_code_parameterless
