import json
import logging

from odoo import SUPERUSER_ID, http
from odoo.http import content_disposition, request

_logger = logging.getLogger(__name__)


class DeltatechTcController(http.Controller):
    """Endpoints called by Terrabit Connect (outbound, cloud model).

    Authentication via the ``X-Station-Key`` header (legacy ``X-Agent-Key`` is
    still accepted for older agents). Plain JSON responses (REST), not JSON-RPC.
    """

    def _json(self, payload, status=200):
        return request.make_json_response(payload, status=status)

    def _station(self):
        headers = request.httprequest.headers
        key = headers.get("X-Station-Key") or headers.get("X-Agent-Key")  # legacy fallback
        return request.env["deltatech.tc.station"]._authenticate(key)

    def _body(self):
        try:
            data = request.httprequest.get_data()
            return json.loads(data) if data else {}
        except (ValueError, TypeError):
            return {}

    @http.route("/tc/heartbeat", type="http", auth="none", methods=["POST"], csrf=False, readonly=False)
    def heartbeat(self, **kw):
        station = self._station()
        if not station:
            return self._json({"error": "unauthorized"}, status=401)
        body = self._body()
        station._touch(info=body)
        if body.get("manual"):
            station._notify_manual_heartbeat()
        return self._json({"ok": True, "station": station.name, "company": station.company_id.name})

    @http.route("/tc/poll", type="http", auth="none", methods=["POST"], csrf=False, readonly=False)
    def poll(self, **kw):
        station = self._station()
        if not station:
            return self._json({"error": "unauthorized"}, status=401)
        station._touch()
        limit = int(self._body().get("limit") or 10)
        jobs = request.env["deltatech.tc.job"].sudo()._claim_for_station(station, limit=limit)
        return self._json({"jobs": [{"id": j.id, "type": j.job_type, "payload": j.payload_dict()} for j in jobs]})

    @http.route("/tc/result", type="http", auth="none", methods=["POST"], csrf=False, readonly=False)
    def result(self, **kw):
        station = self._station()
        if not station:
            return self._json({"error": "unauthorized"}, status=401)
        station._touch()
        body = self._body()
        job_id = body.get("job_id")
        # auth="none" has no env.user; run result processing as the system user so
        # _process_result hooks (e.g. DUK message_post) have a valid singleton user.
        job = (
            request.env["deltatech.tc.job"]
            .with_user(SUPERUSER_ID)
            .search([("id", "=", job_id), ("station_id", "=", station.id)], limit=1)
        )
        if not job:
            return self._json({"error": "job not found"}, status=404)
        job._store_result(
            status=body.get("status") or "done",
            result=body.get("result"),
            error=body.get("error"),
        )
        return self._json({"ok": True, "job_id": job.id, "state": job.state})

    @http.route("/tc/config/<int:station_id>", type="http", auth="user")
    def download_config(self, station_id, **kw):
        """Serve a pre-filled ``agent.conf`` (instance URL + station API key).

        Contains the API key → restricted to Terrabit Connect managers.
        """
        if not request.env.user.has_group("deltatech_tc.group_deltatech_tc_manager"):
            return request.not_found()
        station = request.env["deltatech.tc.station"].sudo().browse(station_id)
        if not station.exists():
            return request.not_found()
        base_url = request.env["ir.config_parameter"].sudo().get_param("web.base.url") or ""
        conf = (
            "# Terrabit Connect (TC) - config generated by Odoo\n"
            f"TERRABIT_ODOO_BASE={base_url}\n"
            f"TERRABIT_STATION_KEY={station.api_key or ''}\n"
        )
        return request.make_response(
            conf,
            headers=[
                ("Content-Type", "text/plain"),
                ("Content-Disposition", content_disposition("station.conf")),
            ],
        )
