[build-system]
requires = [
    "whool",
]
build-backend = "whool.buildapi"

[project]
name = "odoo-addon-deltatech-stock-date"
dependencies = [
    "l10n_ro_stock_account_date @ git+https://github.com/OCA/l10n-romania.git@18.0#egg=l10n_ro_stock_account_date",
]

[project.optional-dependencies]
odoo = [
    "l10n_ro_stock_account_date @ git+https://github.com/OCA/l10n-romania.git@18.0#egg=l10n_ro_stock_account_date",
]
